# Generated by Django 4.1 on 2022-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_rol_id_alter_tarea_id_alter_tareasub_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Contraseña',
            field=models.CharField(default=213123, max_length=50),
            preserve_default=False,
        ),
    ]
