# Generated by Django 4.1 on 2022-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usuario_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_J', models.CharField(max_length=50)),
            ],
        ),
    ]
