# Generated by Django 4.1 on 2022-10-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_jerarquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Jerarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.jerarquia'),
        ),
    ]
