# Generated by Django 4.1 on 2022-10-18 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usuario_jerarquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
