# Generated by Django 4.1 on 2022-10-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_tarea_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'customer'), (3, 'employee')], default=3, null=True),
        ),
    ]
