# Generated by Django 4.1 on 2022-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_usuario_nombre_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Jerarquia',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'customer'), (3, 'employee')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Unidad',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], default=0, null=True),
        ),
    ]
