# Generated by Django 3.1 on 2022-10-24 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20221022_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='Responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea2',
            name='NombreTa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tarea'),
        ),
        migrations.AlterField(
            model_name='tareaace',
            name='Nom_Ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tarea2'),
        ),
        migrations.AlterField(
            model_name='tareasub',
            name='ResponsableS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usuario'),
        ),
        migrations.AlterField(
            model_name='tareasub',
            name='TareaMadreS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tarea'),
        ),
    ]
