# Generated by Django 3.1 on 2022-10-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20221024_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='atraso',
            name='Mensaje',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
