# Generated by Django 3.1 on 2022-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_atraso_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='Mensaje',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
