# Generated by Django 3.1 on 2022-10-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_problema_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Jer1',
            field=models.BooleanField(default=False, verbose_name='Jefe'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Jer2',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Jer3',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Uni1',
            field=models.BooleanField(default=False, verbose_name='Unidad 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Uni2',
            field=models.BooleanField(default=False, verbose_name='Unidad 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Uni3',
            field=models.BooleanField(default=False, verbose_name='Unidad 3'),
        ),
    ]
