# Generated by Django 3.1 on 2022-11-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_estado_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
