# Generated by Django 3.1 on 2022-11-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_tarea_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_tarea',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='estado_tarea',
            name='Mensaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
