# Generated by Django 3.1 on 2022-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20221122_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_tarea',
            name='Nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
