from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('adminpage/', views.admin, name='adminpage'),
    path('customer/', views.customer, name='customer'),
    path('employee/', views.employee, name='employee'),
    path('TerminarTarea/<id>/', views.TerminarTarea, name='TerminarTarea'),
    path('AgregarUsuario/', views.AgregarUsuario, name='AgregarUsuario'),
    path('ModificarUsuario/<id>/', views.ModificarUsuario, name='ModificarUsuario'),
    path('ListarUsuario/', views.ListarUsuario, name='ListarUsuario'),
    path('EliminarUsuario/<id>/', views.EliminarUsuario, name='EliminarUsuario'),
    path('AgregarUnidad/', views.AgregarUnidad, name='AgregarUnidad'),
    path('ListarUnidad/', views.ListarUnidad, name='ListarUnidad'),
    path('ModificarUnidad/<id>/', views.ModificarUnidad, name='ModificarUnidad'),
    path('EliminarUnidad/<id>/', views.EliminarUnidad, name='EliminarUnidad'),
    path('AgregarRol/', views.AgregarRol, name='AgregarRol'),
    path('ListarRol/', views.ListarRol, name='ListarRol'),
    path('ModificarRol/<id>/', views.ModificarRol, name='ModificarRol'),
    path('EliminarRol/<id>/', views.EliminarRol, name='EliminarRol'),
    path('AgregarJerarquia/', views.AgregarJerarquia, name='AgregarJerarquia'),
    path('ListarJerarquia/', views.ListarJerarquia, name='ListarJerarquia'),
    path('ModificarJerarquia/<id>/', views.ModificarJerarquia, name='ModificarJerarquia'),
    path('EliminarJerarquia/<id>/', views.EliminarJerarquia, name='EliminarJerarquia'),
    path('AgregarTarea/', views.AgregarTarea, name='AgregarTarea'),
    path('ModificarTarea/<id>/', views.ModificarTarea, name='ModificarTarea'),
#    path('ListarTarea/', views.ListarTarea, name='ListarTarea'),
    path('EliminarTarea/<id>/', views.EliminarTarea, name='EliminarTarea'),
    path('AgregarTareaSub/', views.AgregarTareaSub, name='AgregarTareaSub'),
    path('ModificarTareaSub/<id>/', views.ModificarTareaSub, name='ModificarTareaSub'),
    path('ListarTareaSub/', views.ListarTareaSub, name='ListarTareaSub'),
    path('EliminarTareaSub/<id>/', views.EliminarTareaSub, name='EliminarTareaSub'),
    path('TareaA/', views.TareaA, name='TareaA'),
    path('detail/<int:id>', views.detail_page, name='detail'),
    path('AgregarAtraso/', views.AgregarAtraso, name='AgregarAtraso'),
    path('ListarAtraso/', views.ListarAtraso, name='ListarAtraso'),
    path('ModificarAtraso/<id>/', views.ModificarAtraso, name='ModificarAtraso'),
    path('EliminarAtraso/<id>/', views.EliminarAtraso, name='EliminarAtraso'),
    path('AgregarProblema/', views.AgregarProblema, name='AgregarProblema'),
    path('ListarProblema/', views.ListarProblema, name='ListarProblema'),
    path('ModificarProblema/<id>/', views.ModificarProblema, name='ModificarProblema'),
    path('EliminarProblema/<id>/', views.EliminarProblema, name='EliminarProblema'),
    path('Listar_Problema/', views.Listar_Problema, name='Listar_Problema'),
    path('Listar_Atraso/', views.Listar_Atraso, name='Listar_Atraso'),
]